"""All Advanced Driver Assist Systems data."""
type Vehicle_ADAS {
  activeAutonomyLevel: Vehicle_ADAS_ActiveAutonomyLevel_Enum
  isAutoPowerOptimize: Boolean
  abs: Vehicle_ADAS_ABS
  obstacleDetection_s: [Vehicle_ADAS_ObstacleDetection]
}

"""Antilock Braking System signals."""
type Vehicle_ADAS_ABS {
  isEngaged: Boolean
  isError: Boolean
}


"""Signals form Obstacle Sensor System."""
type Vehicle_ADAS_ObstacleDetection {
  id: ID!
  distance(unit: LengthUnitEnum = M): Float @range(min: 0, max: 100)
  isEnabled: Boolean
  warningType: Vehicle_ADAS_ObstacleDetection_WarningType_Enum
}
