name: "S2DM Publish"
description: "Automated artifact generation and publishing workflow through S2DM"
author: "COVESA"

inputs:
  repository-path:
    description: "Path to the git repository root"
    required: true

  spec-path:
    description: "Path to the spec directory relative to the root of the repository"
    required: false
    default: "./spec"

  github-token:
    description: "GitHub token for creating releases"
    required: true

  s2dm-path:
    description: "Path where S2DM repository will be checked out"
    required: false
    default: "s2dm"

  concept-namespace:
    description: "Concept namespace for registry"
    required: false
    default: ""

  concept-prefix:
    description: "Concept prefix for registry"
    required: false
    default: ""

  shacl-serialization-format:
    description: "SHACL serialization format"
    required: false
    default: ""

  shacl-shapes-namespace:
    description: "SHACL shapes namespace"
    required: false
    default: ""

  shacl-shapes-prefix:
    description: "SHACL shapes prefix"
    required: false
    default: ""

  shacl-model-namespace:
    description: "SHACL model namespace"
    required: false
    default: ""

  shacl-model-prefix:
    description: "SHACL model prefix"
    required: false
    default: ""

  skos-namespace:
    description: "SKOS namespace"
    required: false
    default: ""

  skos-prefix:
    description: "SKOS prefix"
    required: false
    default: ""

  skos-language:
    description: "SKOS language"
    required: false
    default: ""

  schema-rdf-namespace:
    description: "Namespace URI for schema-rdf concept URIs (e.g. https://covesa.org/s2dm/mydomain#). If provided, schema.nt and schema.ttl are generated."
    required: false
    default: ""

  schema-rdf-prefix:
    description: "Prefix for schema-rdf concept URIs"
    required: false
    default: "ns"

  schema-rdf-language:
    description: "BCP 47 language tag for schema-rdf prefLabels"
    required: false
    default: "en"

outputs:
  version-bump:
    description: "Type of version bump (major, minor, patch, none)"
    value: ${{ steps.version-check.outputs.VERSION_BUMP }}

  latest-tag:
    description: "The latest git tag after release"
    value: ${{ steps.get-latest-tag.outputs.LATEST_TAG }}

  continue:
    description: "Whether migration should continue"
    value: ${{ steps.version-check.outputs.CONTINUE }}

runs:
  using: "composite"
  steps:
    - name: Validate spec directory
      working-directory: ${{ inputs.repository-path }}
      shell: bash
      run: |
        if [ ! -d "${{ inputs.spec-path }}" ]; then
          echo "ERROR: Spec directory '${{ inputs.spec-path }}' not found"
          exit 1
        fi

        if ! find "${{ inputs.spec-path }}" -type f -name "*.graphql" | grep -q .; then
          echo "ERROR: No .graphql files found in spec directory '${{ inputs.spec-path }}'"
          exit 1
        fi

        echo "Spec directory validated successfully"

    - name: Checkout S2DM repository
      uses: actions/checkout@v4
      with:
        repository: COVESA/s2dm
        path: ${{ inputs.s2dm-path }}

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Install S2DM dependencies
      working-directory: ${{ inputs.s2dm-path }}
      shell: bash
      run: |
        uv sync --frozen

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: "20"

    - name: Install Node.js dependencies
      working-directory: ${{ inputs.s2dm-path }}
      shell: bash
      run: npm install

    - name: Activate venv
      shell: bash
      run: |
        echo "${{ github.workspace }}/${{ inputs.s2dm-path }}/.venv/bin" >> $GITHUB_PATH

    - name: Verify S2DM installation
      shell: bash
      run: |
        s2dm --help

    - name: Download latest release
      id: download-release
      working-directory: ${{ inputs.repository-path }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      shell: bash
      run: |
        mkdir -p ${{ github.workspace }}/.previous-release

        # Get the latest release tag
        PREV_TAG=$(gh release view --json tagName --jq .tagName 2>/dev/null || echo "")

        if [ -n "$PREV_TAG" ]; then
          echo "PREV_TAG=$PREV_TAG" >> "$GITHUB_OUTPUT"
          echo "Downloading release: $PREV_TAG"
          gh release download "$PREV_TAG" --pattern "*" --dir ${{ github.workspace }}/.previous-release
        else
          echo "No previous release found"
          echo "PREV_TAG=" >> "$GITHUB_OUTPUT"
        fi

    - name: Extract previous release
      shell: bash
      run: |
        if [ -f "${{ github.workspace }}/.previous-release/release.tar.gz" ]; then
          tar -xzf ${{ github.workspace }}/.previous-release/release.tar.gz -C ${{ github.workspace }}/.previous-release
          rm ${{ github.workspace }}/.previous-release/release.tar.gz
        fi

    - name: Prepare artifacts
      shell: bash
      run: |
        mkdir -p ${{ github.workspace }}/.artifacts/graphql
        mkdir -p ${{ github.workspace }}/.artifacts/jsonschema
        mkdir -p ${{ github.workspace }}/.artifacts/registry
        mkdir -p ${{ github.workspace }}/.artifacts/shacl
        mkdir -p ${{ github.workspace }}/.artifacts/skos
        mkdir -p ${{ github.workspace }}/.artifacts/schema-rdf
        mkdir -p ${{ github.workspace }}/.artifacts/vspec

    - name: Check spec version bump
      id: version-check
      working-directory: ${{ inputs.repository-path }}
      shell: bash
      run: |
        VERSION_BUMP=major
        if [ -f "${{ github.workspace }}/.previous-release/graphql/schema.graphql" ]; then
          echo "Previous schema found"
          VERSION_BUMP=$(s2dm check version-bump -s ${{ inputs.spec-path }} -p ${{ github.workspace }}/.previous-release/graphql/schema.graphql --node-modules-path ${{ github.workspace }}/${{ inputs.s2dm-path }}/node_modules --output-type | tail -n 1)
          if [[ "$VERSION_BUMP" != "none" ]]; then
            echo "CONTINUE=true" >> "$GITHUB_OUTPUT"
          fi
        else
          echo "No previous schema found"
          echo "IS_INITIAL_RELEASE=true" >> "$GITHUB_OUTPUT"
          echo "CONTINUE=true" >> "$GITHUB_OUTPUT"
        fi
        echo "VERSION_BUMP=$VERSION_BUMP" >> "$GITHUB_OUTPUT"

    - name: Compose GraphQL schema
      if: steps.version-check.outputs.CONTINUE == 'true'
      working-directory: ${{ inputs.repository-path }}
      shell: bash
      run: |
        s2dm compose -s ${{ inputs.spec-path }} -o ${{ github.workspace }}/.artifacts/graphql/schema.graphql

    - name: Generate JSON schema
      if: steps.version-check.outputs.CONTINUE == 'true'
      working-directory: ${{ inputs.repository-path }}
      shell: bash
      run: |
        s2dm export jsonschema -S -s ${{ inputs.spec-path }} -o ${{ github.workspace }}/.artifacts/jsonschema/schema.json

    - name: Generate SHACL
      if: steps.version-check.outputs.CONTINUE == 'true'
      working-directory: ${{ inputs.repository-path }}
      shell: bash
      run: |
        CMD="s2dm export shacl -s ${{ inputs.spec-path }} -o ${{ github.workspace }}/.artifacts/shacl/schema.ttl"
        [ -n "${{ inputs.shacl-serialization-format }}" ] && CMD="$CMD --serialization-format '${{ inputs.shacl-serialization-format }}'"
        [ -n "${{ inputs.shacl-shapes-namespace }}" ] && CMD="$CMD --shapes-namespace '${{ inputs.shacl-shapes-namespace }}'"
        [ -n "${{ inputs.shacl-shapes-prefix }}" ] && CMD="$CMD --shapes-namespace-prefix '${{ inputs.shacl-shapes-prefix }}'"
        [ -n "${{ inputs.shacl-model-namespace }}" ] && CMD="$CMD --model-namespace '${{ inputs.shacl-model-namespace }}'"
        [ -n "${{ inputs.shacl-model-prefix }}" ] && CMD="$CMD --model-namespace-prefix '${{ inputs.shacl-model-prefix }}'"
        eval "$CMD"

    - name: Generate SKOS RDF
      if: steps.version-check.outputs.CONTINUE == 'true'
      working-directory: ${{ inputs.repository-path }}
      shell: bash
      run: |
        CMD="s2dm generate skos-skeleton -s ${{ inputs.spec-path }} -o ${{ github.workspace }}/.artifacts/skos/schema.ttl"
        [ -n "${{ inputs.skos-namespace }}" ] && CMD="$CMD --namespace '${{ inputs.skos-namespace }}'"
        [ -n "${{ inputs.skos-prefix }}" ] && CMD="$CMD --prefix '${{ inputs.skos-prefix }}'"
        [ -n "${{ inputs.skos-language }}" ] && CMD="$CMD --language '${{ inputs.skos-language }}'"
        eval "$CMD"

    - name: Generate schema RDF
      if: steps.version-check.outputs.CONTINUE == 'true' && inputs.schema-rdf-namespace != ''
      working-directory: ${{ inputs.repository-path }}
      shell: bash
      run: |
        CMD="s2dm generate schema-rdf -s ${{ inputs.spec-path }} -o ${{ github.workspace }}/.artifacts/schema-rdf --namespace '${{ inputs.schema-rdf-namespace }}'"
        [ -n "${{ inputs.schema-rdf-prefix }}" ] && CMD="$CMD --prefix '${{ inputs.schema-rdf-prefix }}'"
        [ -n "${{ inputs.schema-rdf-language }}" ] && CMD="$CMD --language '${{ inputs.schema-rdf-language }}'"
        eval "$CMD"

    - name: Generate VSpec
      if: steps.version-check.outputs.CONTINUE == 'true'
      working-directory: ${{ inputs.repository-path }}
      shell: bash
      run: |
        s2dm export vspec -s ${{ inputs.spec-path }} -o ${{ github.workspace }}/.artifacts/vspec/schema.vspec

    - name: Bump version and push tags
      if: steps.version-check.outputs.CONTINUE == 'true'
      working-directory: ${{ inputs.repository-path }}
      shell: bash
      run: |
        git config --local user.email "s2dm-automation-action@covesa.global"
        git config --local user.name "S2DM Automation Action"
        bump-my-version bump ${{ steps.version-check.outputs.VERSION_BUMP }} --config-file ./.bumpversion.toml
        git push origin ${{ github.ref_name }}
        git push origin --tags

    - name: Get latest tag
      if: steps.version-check.outputs.CONTINUE == 'true'
      id: get-latest-tag
      working-directory: ${{ inputs.repository-path }}
      shell: bash
      run: |
        LATEST_TAG=$(git describe --tags --abbrev=0)
        echo "LATEST_TAG=$LATEST_TAG" >> "$GITHUB_OUTPUT"

    - name: Generate GraphQL diff
      if: steps.version-check.outputs.CONTINUE == 'true' && steps.version-check.outputs.IS_INITIAL_RELEASE != 'true'
      id: generate-diff
      shell: bash
      run: |
        s2dm diff graphql \
          -s ${{ github.workspace }}/.previous-release/graphql/schema.graphql \
          -v ${{ inputs.spec-path }} \
          --node-modules-path ${{ github.workspace }}/${{ inputs.s2dm-path }}/node_modules \
          -o ${{ github.workspace }}/.artifacts/diff.json || true

        # Check if diff file exists and has changes
        if [ -f "${{ github.workspace }}/.artifacts/diff.json" ]; then
          # Check if diff file is not empty and contains actual changes (not just empty array "[]")
          # Use Python to parse JSON and check array length
          DIFF_COUNT=$(python3 -c "import json; f=open('${{ github.workspace }}/.artifacts/diff.json'); data=json.load(f); print(len(data)) if isinstance(data, list) else print(0)" 2>/dev/null || echo "0")
          if [ "$DIFF_COUNT" -gt 0 ]; then
            echo "HAS_CHANGES=true" >> "$GITHUB_OUTPUT"
            echo "Found $DIFF_COUNT change(s) in schema"
          else
            echo "HAS_CHANGES=false" >> "$GITHUB_OUTPUT"
            echo "No schema changes detected (diff file is empty or contains no changes)"
          fi
        else
          echo "HAS_CHANGES=false" >> "$GITHUB_OUTPUT"
          echo "Diff file not generated (no previous schema or error)"
        fi

    - name: Initialize registry
      if: steps.version-check.outputs.CONTINUE == 'true' && steps.version-check.outputs.IS_INITIAL_RELEASE == 'true'
      working-directory: ${{ inputs.repository-path }}
      shell: bash
      run: |
        LATEST_TAG="${{ steps.get-latest-tag.outputs.LATEST_TAG }}"
        echo "Initializing registry with version tag: $LATEST_TAG"

        CMD="s2dm registry init -s ${{ inputs.spec-path }} -o ${{ github.workspace }}/.artifacts/registry/registry.json --version-tag $LATEST_TAG"
        [ -n "${{ inputs.concept-namespace }}" ] && CMD="$CMD --concept-namespace '${{ inputs.concept-namespace }}'"
        [ -n "${{ inputs.concept-prefix }}" ] && CMD="$CMD --concept-prefix '${{ inputs.concept-prefix }}'"
        eval "$CMD"

    - name: Update registry
      if: steps.version-check.outputs.CONTINUE == 'true' && steps.version-check.outputs.IS_INITIAL_RELEASE != 'true' && steps.generate-diff.outputs.HAS_CHANGES == 'true'
      working-directory: ${{ inputs.repository-path }}
      shell: bash
      run: |
        # Use the previous release tag from downloaded artifacts
        PREV_TAG="${{ steps.download-release.outputs.PREV_TAG }}"
        LATEST_TAG="${{ steps.get-latest-tag.outputs.LATEST_TAG }}"

        echo "Using previous tag: $PREV_TAG for registry files"
        echo "New version tag: $LATEST_TAG"

        PREV_IDS="${{ github.workspace }}/.previous-release/registry/variant_ids_${PREV_TAG}.json"
        PREV_REGISTRY="${{ github.workspace }}/.previous-release/registry/registry_${PREV_TAG}.json"

        # Fallback to files without version suffix if versioned files don't exist
        [ ! -f "$PREV_IDS" ] && PREV_IDS="${{ github.workspace }}/.previous-release/registry/variant_ids.json"
        [ ! -f "$PREV_REGISTRY" ] && PREV_REGISTRY="${{ github.workspace }}/.previous-release/registry/registry.json"

        # Diff file is required for registry update (we only run this step if HAS_CHANGES is true)
        if [ ! -f "${{ github.workspace }}/.artifacts/diff.json" ]; then
          echo "Error: Diff file is required for registry update but was not found"
          exit 1
        fi

        CMD="s2dm registry update -s ${{ inputs.spec-path }} -sh $PREV_REGISTRY -o ${{ github.workspace }}/.artifacts/registry/registry.json --previous-ids $PREV_IDS --version-tag $LATEST_TAG --diff-file ${{ github.workspace }}/.artifacts/diff.json"

        [ -n "${{ inputs.concept-namespace }}" ] && CMD="$CMD --concept-namespace '${{ inputs.concept-namespace }}'"
        [ -n "${{ inputs.concept-prefix }}" ] && CMD="$CMD --concept-prefix '${{ inputs.concept-prefix }}'"
        eval "$CMD"

    - name: Skip registry update (no changes)
      if: steps.version-check.outputs.CONTINUE == 'true' && steps.version-check.outputs.IS_INITIAL_RELEASE != 'true' && steps.generate-diff.outputs.HAS_CHANGES == 'false'
      shell: bash
      run: |
        echo "No schema changes detected, skipping registry update"
        echo "Registry files from previous release will be reused"

    - name: Abort release (no changes detected)
      if: steps.version-check.outputs.CONTINUE == 'true' && steps.version-check.outputs.IS_INITIAL_RELEASE != 'true' && steps.generate-diff.outputs.HAS_CHANGES == 'false'
      shell: bash
      run: |
        echo "ERROR: No schema changes detected but version check indicated changes"
        echo "This should not happen - aborting release to prevent creating a release with no changes"
        exit 1

    - name: Verify history directory
      if: steps.version-check.outputs.CONTINUE == 'true'
      shell: bash
      run: |
        if [ -d "${{ github.workspace }}/.artifacts/registry/history" ]; then
          echo "History directory found, will be included in release"
        else
          echo "No history directory found (this is normal for releases with no changes)"
        fi

    - name: Create release
      if: steps.version-check.outputs.CONTINUE == 'true' && (steps.version-check.outputs.IS_INITIAL_RELEASE == 'true' || steps.generate-diff.outputs.HAS_CHANGES == 'true')
      working-directory: ${{ inputs.repository-path }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      shell: bash
      run: |
        LATEST_TAG="${{ steps.get-latest-tag.outputs.LATEST_TAG }}"
        tar -czf release.tar.gz -C ${{ github.workspace }}/.artifacts .
        gh release create "${LATEST_TAG}" \
          --title "Release ${LATEST_TAG}" \
          --notes "This release contains the artifacts from the automated publishing workflow." \
          release.tar.gz
